In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
chr_df = pd.read_excel('../data/2025 County Health Rankings Data - v4.xlsx', 
                        sheet_name=1, 
                        header=1)
print("CHR Shape:", chr_df.shape)
chr_df.head()

CHR Shape: (3210, 225)

,FIPS,State,County,Unreliable,Deaths,Years of Potential Life Lost Rate,95% CI - Low,95% CI - High,National Z-Score,YPLL Rate (Hispanic (all races)),...,Injury Death Rate (Non-Hispanic 2+ races) 95% CI - Low,Injury Death Rate (Non-Hispanic 2+ races) 95% CI - High,Injury Death Rate (Non-Hispanic White),Injury Death Rate (Non-Hispanic White) 95% CI - Low,Injury Death Rate (Non-Hispanic White) 95% CI - High,# Associations,Social Association Rate,National Z-Score.27,% Household Income Required for Child Care Expenses,National Z-Score.28
0,1000,Alabama,NaN,NaN,102760.0,11853.247248,11744.014820,11962.479676,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5916.0,11.658760,NaN,25.547114,NaN
1,1001,Alabama,Autauga,NaN,1008.0,9938.263382,9021.297133,10855.229632,-0.144182,NaN,...,NaN,NaN,66.353516,55.322574,77.384459,67.0,11.211700,0.043429,21.835108,-0.961825
2,1003,Alabama,Baldwin,NaN,3944.0,8957.112686,8499.339223,9414.886148,-0.400274,4636.48424,...,NaN,NaN,86.954622,81.060141,92.849104,239.0,9.698298,0.308739,19.354057,-1.316051
3,1005,Alabama,Barbour,NaN,587.0,12738.656137,11133.499025,14343.813250,0.586752,NaN,...,NaN,NaN,92.500356,69.083690,121.301910,22.0,8.904720,0.447859,28.579628,0.001105
4,1007,Alabama,Bibb,NaN,509.0,11708.948038,10166.716823,13251.179253,0.317987,NaN,...,NaN,NaN,110.157489,88.691939,135.248986,19.0,8.634401,0.495248,26.582776,-0.283990

In [4]:
chr_df = chr_df[chr_df['County'].notna()]

chr_df['FIPS'] = chr_df['FIPS'].astype(str).str.zfill(5)

print("New CHR shape:", chr_df.shape)
chr_df[['FIPS', 'State', 'County']].head()

New CHR shape: (3159, 225)

    FIPS    State   County
1  01001  Alabama  Autauga
2  01003  Alabama  Baldwin
3  01005  Alabama  Barbour
4  01007  Alabama     Bibb
5  01009  Alabama   Blount

In [5]:
chr_df['FIPS'].str.len().value_counts()

FIPS
5    3159
Name: count, dtype: int64

In [6]:
southern_states = ['Alabama', 'Arkansas', 'Florida', 'Georgia', 
                   'Kentucky', 'Louisiana', 'Mississippi', 
                   'North Carolina', 'South Carolina', 
                   'Tennessee', 'Texas', 'Virginia', 'West Virginia']

chr_south = chr_df[chr_df['State'].isin(southern_states)]
print(chr_south.shape)

(1318, 225)

In [7]:
hpsa_df = pd.read_csv('../data/BCD_HPSA_FCT_DET_PC.csv', encoding='latin-1', low_memory=False)
print("HPSA Shape:", hpsa_df.shape)
hpsa_df.head()

HPSA Shape: (79056, 66)

,HPSA Name,HPSA ID,Designation Type,HPSA Discipline Class,HPSA Score,PC MCTA Score,Primary State Abbreviation,HPSA Status,HPSA Designation Date,HPSA Designation Last Update Date,...,Rural Status Code,State Abbreviation,State and County Federal Information Processing Standard Code,State FIPS Code,State Name,U.S. - Mexico Border 100 Kilometer Indicator,U.S. - Mexico Border County Indicator,Data Warehouse Record Create Date,Data Warehouse Record Create Date Text,Unnamed: 65
0,RUTGERS THE STATE UNIVERSITY OF NEW JERSEY,1347143042,Federally Qualified Health Center,Primary Care,6,10.0,NJ,Designated,05/17/2024,05/13/2025,...,N,NJ,34013,34,New Jersey,N,N,06/11/2026,2026/06/11,NaN
1,Salem City SA,1347035283,Geographic HPSA,Primary Care,18,15.0,NJ,Designated,08/07/2025,08/07/2025,...,N,NJ,34033,34,New Jersey,N,N,06/11/2026,2026/06/11,NaN
2,Bayside State Prison,1346602983,Correctional Facility,Primary Care,12,0.0,NJ,Designated,05/30/2013,05/24/2022,...,R,NJ,34011,34,New Jersey,N,N,06/11/2026,2026/06/11,NaN
3,South Essex County SA,1346542462,Geographic HPSA,Primary Care,13,9.0,NJ,Designated,02/25/2026,02/25/2026,...,N,NJ,34013,34,New Jersey,N,N,06/11/2026,2026/06/11,NaN
4,South Essex County SA,1346542462,Geographic HPSA,Primary Care,13,9.0,NJ,Designated,02/25/2026,02/25/2026,...,N,NJ,34013,34,New Jersey,N,N,06/11/2026,2026/06/11,NaN

In [8]:
for col in hpsa_df.columns[[29, 53, 59]]:
    print(col, hpsa_df[col].apply(type).value_counts())

Common State FIPS Code Common State FIPS Code
<class 'str'>    79056
Name: count, dtype: int64
Primary State FIPS Code Primary State FIPS Code
<class 'str'>    79056
Name: count, dtype: int64
State FIPS Code State FIPS Code
<class 'str'>    79056
Name: count, dtype: int64

In [9]:
hpsa_df.duplicated().sum()

np.int64(4)

In [10]:
hpsa_df['State FIPS Code'].str.len().value_counts()

State FIPS Code
2    79056
Name: count, dtype: int64